name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build Core Workspace
        run: npm run build
        working-directory: ./packages/core

      - name: Publish to NPM
        run: npm publish --access public --provenance
        working-directory: ./packages/core